# Generated by Django 5.2.6 on 2025-09-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_allow_null_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
