# Generated by Django 5.2.6 on 2025-09-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_websitecontent_email'),
    ]

    operations = [
        # Rename existing fields to banner1
        migrations.RenameField(
            model_name='websitecontent',
            old_name='banner_image',
            new_name='banner1_image',
        ),
        migrations.RenameField(
            model_name='websitecontent',
            old_name='banner_text',
            new_name='banner1_text',
        ),
        migrations.RenameField(
            model_name='websitecontent',
            old_name='banner_link',
            new_name='banner1_link',
        ),
        
        # Add banner2 fields
        migrations.AddField(
            model_name='websitecontent',
            name='banner2_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='banner2_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='banner2_link',
            field=models.URLField(blank=True),
        ),
        
        # Add banner3 fields
        migrations.AddField(
            model_name='websitecontent',
            name='banner3_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='banner3_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='banner3_link',
            field=models.URLField(blank=True),
        ),
    ]
