# Generated by Django 5.2.6 on 2025-09-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_auto_20250917_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecontent',
            name='banner1_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='banner2_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='banner3_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
