# Generated by Django 5.2.6 on 2025-09-17 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_chatroom_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Authenticated user (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
