# Generated by Django 5.2.6 on 2025-09-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='about_us_picture',
            field=models.ImageField(blank=True, null=True, upload_to='store/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_name',
            field=models.CharField(default='sppix', max_length=200),
        ),
    ]
