# Generated by Django 5.2.6 on 2025-09-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_storesettings_about_us_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon for the website (recommended size: 32x32 or 16x16 pixels)', null=True, upload_to='store/'),
        ),
    ]
