# Generated by Django 5.2.6 on 2025-09-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_storesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='country',
            field=models.CharField(blank=True, help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='postcode',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address', max_length=200),
        ),
    ]
