# Generated by Django 5.2.6 on 2025-09-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_storesettings_city_storesettings_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Store email address', max_length=254),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='monday_friday_hours',
            field=models.CharField(blank=True, help_text="Monday - Friday hours (e.g., '9:00 AM - 6:00 PM')", max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='phone',
            field=models.CharField(blank=True, help_text='Store phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='saturday_hours',
            field=models.CharField(blank=True, help_text="Saturday hours (e.g., '10:00 AM - 4:00 PM')", max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sunday_hours',
            field=models.CharField(blank=True, help_text="Sunday hours (e.g., 'Closed')", max_length=100),
        ),
    ]
