# Generated by Django 5.2.6 on 2025-09-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_storesettings_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitecontent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='websitecontent',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='country',
            field=models.CharField(blank=True, help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='phone',
            field=models.CharField(blank=True, help_text='Store phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='postcode',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address', max_length=200),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='email',
            field=models.EmailField(blank=True, help_text='Store email address', max_length=254),
        ),
    ]
