# Generated by Django 5.2.6 on 2025-09-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_remove_websitecontent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='deal1_description',
            field=models.TextField(blank=True, help_text='Deal product 1 description'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='deal1_discount',
            field=models.CharField(blank=True, help_text="Deal product 1 discount (e.g., 'Up to 50% Off')", max_length=50),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='deal1_end_date',
            field=models.DateTimeField(blank=True, help_text='Deal product 1 end date', null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='deal1_image',
            field=models.ImageField(blank=True, help_text='Deal product 1 image', null=True, upload_to='deals/'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='deal1_subtitle',
            field=models.CharField(blank=True, help_text='Deal product 1 subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='deal1_title',
            field=models.CharField(blank=True, help_text='Deal product 1 title', max_length=200),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='deal2_description',
            field=models.TextField(blank=True, help_text='Deal product 2 description'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='deal2_discount',
            field=models.CharField(blank=True, help_text="Deal product 2 discount (e.g., 'Up to 50% Off')", max_length=50),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='deal2_end_date',
            field=models.DateTimeField(blank=True, help_text='Deal product 2 end date', null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='deal2_image',
            field=models.ImageField(blank=True, help_text='Deal product 2 image', null=True, upload_to='deals/'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='deal2_subtitle',
            field=models.CharField(blank=True, help_text='Deal product 2 subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='deal2_title',
            field=models.CharField(blank=True, help_text='Deal product 2 title', max_length=200),
        ),
    ]
