# Generated by Django 5.2.6 on 2025-09-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_websitecontent_deal1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='availability',
            field=models.CharField(blank=True, help_text='Service availability information', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_info',
            field=models.JSONField(blank=True, default=dict, help_text='Contact information (phone, email)'),
        ),
        migrations.AddField(
            model_name='service',
            name='included_features',
            field=models.JSONField(blank=True, default=list, help_text='List of included features'),
        ),
        migrations.AddField(
            model_name='service',
            name='key_features',
            field=models.JSONField(blank=True, default=list, help_text='Key service features'),
        ),
        migrations.AddField(
            model_name='service',
            name='overview',
            field=models.TextField(blank=True, help_text='Detailed service overview'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_steps',
            field=models.JSONField(blank=True, default=list, help_text='Service process steps with durations'),
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Service rating (0.0-5.0)', max_digits=2),
        ),
        migrations.AddField(
            model_name='service',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of reviews'),
        ),
    ]
