# Generated by Django 5.2.6 on 2025-09-19 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_servicecategory_service_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Name of the reviewer', max_length=200)),
                ('rating', models.PositiveSmallIntegerField(help_text='Overall rating (1-5)')),
                ('comment', models.TextField(blank=True)),
                ('service_quality', models.PositiveSmallIntegerField(default=0, help_text='Service quality rating (1-5)')),
                ('communication', models.PositiveSmallIntegerField(default=0, help_text='Communication rating (1-5)')),
                ('timeliness', models.PositiveSmallIntegerField(default=0, help_text='Timeliness rating (1-5)')),
                ('value_for_money', models.PositiveSmallIntegerField(default=0, help_text='Value for money rating (1-5)')),
                ('verified', models.BooleanField(default=False, help_text='Whether this is a verified purchase/service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='adminpanel.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
