# Generated by Django 5.2.6 on 2025-09-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_name',
            field=models.CharField(default='Anonymous', help_text='Name of the reviewer', max_length=200),
        ),
    ]
