# Generated by Django 5.2.6 on 2025-09-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0028_add_unique_constraint_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this product has been viewed'),
        ),
        migrations.AddField(
            model_name='service',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this service has been viewed'),
        ),
    ]
