# Generated by Django 5.2.6 on 2025-09-19 19:14

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Brand = apps.get_model('adminpanel', 'Brand')
    Category = apps.get_model('adminpanel', 'Category')
    
    # Populate brand slugs
    for brand in Brand.objects.all():
        if not brand.slug:
            base_slug = slugify(brand.name)
            slug = base_slug
            counter = 1
            while Brand.objects.filter(slug=slug).exclude(pk=brand.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            brand.slug = slug
            brand.save()
    
    # Populate category slugs
    for category in Category.objects.all():
        if not category.slug:
            base_slug = slugify(category.name)
            slug = base_slug
            counter = 1
            while Category.objects.filter(slug=slug, parent=category.parent).exclude(pk=category.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            category.slug = slug
            category.save()


def reverse_populate_slugs(apps, schema_editor):
    Brand = apps.get_model('adminpanel', 'Brand')
    Category = apps.get_model('adminpanel', 'Category')
    
    # Clear slugs
    Brand.objects.update(slug=None)
    Category.objects.update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0030_brand_slug_category_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
