# Generated by Django 5.2.6 on 2025-09-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0031_populate_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top_selling',
            field=models.BooleanField(default=False, help_text='Mark this product as top selling to display on home page'),
        ),
    ]
