# Generated by Django 5.2.6 on 2025-09-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0032_add_is_top_selling_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isNew',
            field=models.BooleanField(default=False, help_text='Mark this product as new arrival to display in new products section'),
        ),
    ]
