# Generated by Django 5.2.6 on 2025-09-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_enhance_order_model'),
        ('adminpanel', '0033_product_isnew'),
    ]

    operations = [
    ]
