# Generated by Django 5.2.6 on 2025-09-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0035_add_updated_at_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='express_shipping_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Express Shipping rate (2-3 business days)', max_digits=6),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='standard_shipping_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standard Shipping rate (5-7 business days)', max_digits=6),
        ),
    ]
