# Generated by Django 5.2.6 on 2025-09-22 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0040_alter_storesettings_currency_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, help_text='User who sent the message (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
