# Generated by Django 5.2.6 on 2025-09-23 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0041_add_sender_user_to_chatmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
    ]
