# Generated by Django 5.2.6 on 2025-09-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0042_remove_chatroom_user_delete_chatmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Brand logo/image", null=True, upload_to="brands/"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Category image (typically used for grandchild categories)",
                null=True,
                upload_to="categories/",
            ),
        ),
    ]
