# Generated by Django 5.2.6 on 2025-09-23 16:17

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0043_brand_image_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="adminpanel.servicecategory",
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name="servicecategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("parent"),
                name="uniq_service_category_name_per_parent_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecategory",
            constraint=models.UniqueConstraint(
                models.F("slug"),
                models.F("parent"),
                name="uniq_service_category_slug_per_parent",
            ),
        ),
    ]
