# Generated by Django 5.2.6 on 2025-09-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0044_add_service_category_hierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Category image",
                null=True,
                upload_to="service_categories/",
            ),
        ),
    ]
