# Generated by Django 5.2.6 on 2025-09-26 12:35

from django.db import migrations
from django.utils import timezone


def populate_order_numbers(apps, schema_editor):
    Order = apps.get_model('adminpanel', 'Order')
    
    for order in Order.objects.filter(order_number__isnull=True):
        # Generate order number for existing orders
        order.order_number = f"ORD-{timezone.now().strftime('%Y%m%d')}-{str(order.id).zfill(6)}"
        order.save(update_fields=['order_number'])


def reverse_populate_order_numbers(apps, schema_editor):
    Order = apps.get_model('adminpanel', 'Order')
    Order.objects.update(order_number=None)


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0046_alter_order_options_order_billing_address_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_order_numbers, reverse_populate_order_numbers),
    ]
