# Generated by Django 5.2.6 on 2025-09-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0047_populate_order_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                blank=True,
                help_text="Selected shipping method (standard, express, etc.)",
                max_length=50,
            ),
        ),
    ]
