# Generated by Django 5.2.6 on 2025-09-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0048_order_shipping_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecontent",
            name="home_hero_subtitle",
            field=models.TextField(
                blank=True, help_text="Hero section subtitle text on home page"
            ),
        ),
        migrations.AddField(
            model_name="websitecontent",
            name="home_services_description",
            field=models.TextField(
                blank=True, help_text="Services section description text on home page"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
