# Generated by Django 5.2.6 on 2025-09-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0049_websitecontent_home_hero_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecontent",
            name="home_categories_description",
            field=models.TextField(
                blank=True,
                help_text="Product categories section description text on home page",
            ),
        ),
    ]
