# Generated by Django 5.2.6 on 2025-09-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0050_websitecontent_home_categories_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecontent",
            name="services_page_description",
            field=models.TextField(
                blank=True, help_text="Description text for the services page"
            ),
        ),
    ]
