# Generated by Django 5.2.6 on 2025-09-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0051_websitecontent_services_page_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecontent",
            name="services_page_title",
            field=models.CharField(
                blank=True, help_text="Title text for the services page", max_length=200
            ),
        ),
    ]
