# Generated by Django 5.2.6 on 2025-09-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0052_websitecontent_services_page_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slogan",
            field=models.TextField(
                blank=True,
                help_text="Dynamic slogan for this category. Will be displayed on category pages.",
                null=True,
            ),
        ),
    ]
