# Generated by Django 5.2.6 on 2025-10-07 02:22

import adminpanel.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0053_category_slogan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["-is_main", "-created_at"]},
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(
                default=False, help_text="Mark this as the main product image"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Brand logo/image",
                null=True,
                upload_to=adminpanel.upload_paths.brand_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Category image (typically used for grandchild categories)",
                null=True,
                upload_to=adminpanel.upload_paths.category_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Category image",
                null=True,
                upload_to=adminpanel.upload_paths.service_category_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="image",
            field=models.ImageField(
                upload_to=adminpanel.upload_paths.service_image_path
            ),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="about_us_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=adminpanel.upload_paths.store_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Favicon for the website (recommended size: 32x32 or 16x16 pixels)",
                null=True,
                upload_to=adminpanel.upload_paths.store_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="store_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=adminpanel.upload_paths.store_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="banner1_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=adminpanel.upload_paths.banner_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="banner2_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=adminpanel.upload_paths.banner_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="banner3_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=adminpanel.upload_paths.banner_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="deal1_image",
            field=models.ImageField(
                blank=True,
                help_text="Deal product 1 image",
                null=True,
                upload_to=adminpanel.upload_paths.deal_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="deal2_image",
            field=models.ImageField(
                blank=True,
                help_text="Deal product 2 image",
                null=True,
                upload_to=adminpanel.upload_paths.deal_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=adminpanel.upload_paths.logo_image_path
            ),
        ),
    ]
