# Generated by Django 5.2.6 on 2025-10-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0054_add_main_image_flag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serviceimage",
            options={"ordering": ["-is_main", "-created_at"]},
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="is_main",
            field=models.BooleanField(
                default=False, help_text="Mark this as the main service image"
            ),
        ),
    ]
