# Generated by Django 5.2.6 on 2025-10-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0055_alter_serviceimage_options_serviceimage_is_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceimage",
            name="image_hash",
            field=models.CharField(
                blank=True,
                help_text="MD5 hash of image content for duplicate detection",
                max_length=64,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceimage",
            unique_together={("service", "image_hash")},
        ),
    ]
