# Generated by Django 5.2.6 on 2025-10-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0056_serviceimage_image_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image_hash",
            field=models.CharField(
                blank=True,
                help_text="MD5 hash of image content for duplicate detection",
                max_length=64,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productimage",
            unique_together={("product", "image_hash")},
        ),
    ]
