# Generated by Django 5.0.1 on 2024-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0058_alter_orderitem_options_chatroom_chatmessage'),  # Updated to correct dependency
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status__in', ['active', 'waiting'])),
                fields=('user',),
                name='unique_active_user_room'
            ),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status__in', ['active', 'waiting']), ('user__isnull', True)),
                fields=('customer_session',),
                name='unique_active_session_room'
            ),
        ),
    ]
