# Generated by Django 4.2.7 on 2025-10-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0061_add_chat_room_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="serviceimage",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="productimage",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="serviceimage",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Brand logo/image", null=True, upload_to="brands/"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Category image (typically used for grandchild categories)",
                null=True,
                upload_to="categories/",
            ),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Category image",
                null=True,
                upload_to="service_categories/",
            ),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="image",
            field=models.ImageField(upload_to="services/"),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="about_us_picture",
            field=models.ImageField(blank=True, null=True, upload_to="store/"),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Favicon for the website (recommended size: 32x32 or 16x16 pixels)",
                null=True,
                upload_to="store/",
            ),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="store_logo",
            field=models.ImageField(blank=True, null=True, upload_to="store/"),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="banner1_image",
            field=models.ImageField(blank=True, null=True, upload_to="banner/"),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="banner2_image",
            field=models.ImageField(blank=True, null=True, upload_to="banner/"),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="banner3_image",
            field=models.ImageField(blank=True, null=True, upload_to="banner/"),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="deal1_image",
            field=models.ImageField(
                blank=True,
                help_text="Deal product 1 image",
                null=True,
                upload_to="deals/",
            ),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="deal2_image",
            field=models.ImageField(
                blank=True,
                help_text="Deal product 2 image",
                null=True,
                upload_to="deals/",
            ),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logo/"),
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="image_hash",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="is_main",
        ),
        migrations.RemoveField(
            model_name="serviceimage",
            name="image_hash",
        ),
        migrations.RemoveField(
            model_name="serviceimage",
            name="is_main",
        ),
    ]
