# Generated by Django 4.2.7 on 2025-10-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "adminpanel",
            "0062_alter_orderitem_options_alter_productimage_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serviceimage",
            options={"ordering": ["-is_main", "-created_at"]},
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="image_hash",
            field=models.CharField(
                blank=True,
                help_text="MD5 hash of image content for duplicate detection",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="is_main",
            field=models.BooleanField(
                default=False, help_text="Mark this as the main service image"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceimage",
            unique_together={("service", "image_hash")},
        ),
    ]
