# Generated by Django 4.2.7 on 2025-10-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "adminpanel",
            "0063_alter_serviceimage_options_serviceimage_image_hash_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="serviceimage",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="serviceimage",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
        migrations.RemoveField(
            model_name="serviceimage",
            name="image_hash",
        ),
    ]
