# Generated by Django 4.2.7 on 2025-10-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0065_enable_chat_system"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["-is_main", "-created_at"]},
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(
                default=False, help_text="Mark this as the main product image"
            ),
        ),
    ]
