# Generated by Django 4.2.7 on 2025-10-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0066_add_is_main_to_product_image"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE adminpanel_productimage ALTER COLUMN is_main SET DEFAULT 0;",
            reverse_sql="ALTER TABLE adminpanel_productimage ALTER COLUMN is_main DROP DEFAULT;"
        ),
    ]
